### ISSUE TITLE
AnimeHay and Phim Moi issue

### ISSUE THREAD

**Issue by sviet2k** [billythekids/plugin.video.bimozie#1]
Hi Billy,

I would like to let you know that the PhimMoi cannot get the Movie list and the AnimeHay cannot play the Episode links.

I use Kodi 18.1 with Android 7.

Thanks a lot for your hard work. 👍

**Comment by billythekids** [comment]
Thank for reporting 
I did test again on phimmoi, it still works fine. Can you give me more details?
Btw i'm still working on animehay, new release will come out soon

**Comment by sviet2k** [comment]
Thanks for quick answer.
When I select phimoi, I only see the Search option. No other option to select drama.
My Bimozie version is 0.1.4 from the repo. I guess the version is wrong.
I have updated manually to version 0.1.8 but the problem is still there: there is only the Search option on the PhimMoi page.

Thank you

**Comment by sviet2k** [comment]
Hi Billy,

I know why PMoi does not display the content because there is Geo block. (I am in Canada). Can you please add the vn.php in Request Header to by pass the Geo Block ?

Thank you.

**Comment by billythekids** [comment]
It would be great if you can create a pull request.
I'm a bit busy these day

**Comment by sviet2k** [comment]
I cannot do a pull request but here is the change of plugin for PMoi. I modified the plugin to use the Local Request.

[PMoi-plugin.zip](https://github.com/billythekids/plugin.video.bimozie/files/2942132/PMoi-plugin.zip)

Please 'merge' it when you have time.
Thanks.
Note: you are really good to find out (Reverse engineering) the way to decrypt the key 👍

**Comment by billythekids** [comment]
Issue fixed
