### ISSUE TITLE
Kenh88 site is back, link is not working

### ISSUE THREAD

**Issue by minhgi** [billythekids/plugin.video.bimozie#12]
Hi Billy... seem the sit eis back but none of the link is working.  I use this site mostly to watch the viet phim

**Comment by billythekids** [comment]
Hi Minhgi, 

I did try on kenh88 but none of links provided from them are working.
Site is inactive very long time. So i wont support this site any longer, hope you understand it. 
Btw i'm happy to support other site if you know any that working for you. Feel free to create new issue and request for it.
