### ISSUE TITLE
Tvhay.org only works with server R.

### ISSUE THREAD

**Issue by thanhnhaxinhdep** [billythekids/plugin.video.bimozie#14]
Hi Billy, 
Firstly, I want to say thank you for your dedication to the add on. Secondly, I find out that although some films on tvhay.org have many servers but the add on is likely to work on R. server only, which is a little bit slow source. Sometimes I find server B. but they only last for 1 or 2 day. 
May you fix it so that it can be compatible with other servers? 
Thank you very much.

**Comment by billythekids** [comment]
Its complicated to get other links on tvhay, so i decided not to support it for now. 
Anyone can contribute on my project, and i'm very happy with it

**Comment by thanhnhaxinhdep** [comment]
I found server B on the add on already. Thank you so much for the improvements.
