### ISSUE TITLE
Lỗi tìm kiếm 

### ISSUE THREAD

**Issue by vuduytaidb** [billythekids/plugin.video.bimozie#15]
Add-on bị lỗi tìm kiếm khi vào tìm một bộ phim thì không ra kết quả rù tìm kiếm chung hay tìm kiếm riêng từng kho đều không hiện kết quả. Cho dù phim đấy vẫn có trong mục thể loại, quốc tế thì trong thanh tìm kiếm vẫn không có.

**Comment by billythekids** [comment]
Bạn cung cấp cho mình logs của kodi đc ko? Cái addon cần phải có quyền truy cập file để có thể lưu lại các keywork. Do đó khi cài đặt kodi phải cho phép quyền truy cập file mới đc.

**Comment by billythekids** [comment]
Tạm close lại vì ko thấy có trả lời
