### ISSUE TITLE
Phimnhe: manga link stop working

### ISSUE THREAD

**Issue by sviet2k** [billythekids/plugin.video.bimozie#16]
Hi Billy,

I would like to let you know that the addon cannot play manga123 link in Phimnhe (Phimgi).
I tried Streamlink to play the link but failed.
Please take a look when you have time.

Thanks

**Comment by billythekids** [comment]
Can you provide the movie title so i can test with it. I couldnt find this kind of link anywhere

**Comment by sviet2k** [comment]
In: Thợ Săn Quái Vật (Phần 1) Ep: 2
The Manga link:
h t t p s://load balance .manga123.net/hls/ff2f4362f622f6b04205cd1ad2e65bdc/ff2f4362f622f6b04205cd1ad2e65bdc.m3u8

**Comment by boxkim14** [comment]
Site was removed.
How can I close this? :)

**Comment by billythekids** [comment]
Fixed
