### ISSUE TITLE
Phim Moi - Cannot play dramas

### ISSUE THREAD

**Issue by sviet2k** [billythekids/plugin.video.bimozie#18]
Hi billy,

I hope you are doing well 👍 
Currently, I can access to phim moi from foreign county but I cannot play dramas.
Ex: ht tp://www.phim moizz.net/phim/cao-oc-ma-quai-toa-thap-chet-11356/xem-phim.html
The episode can be played in the web browser but not in the addon.
Can you please take a look on this when you have time?

Thank you.

**Comment by billythekids** [comment]
it seems working for me, could you please attach your logs?

**Comment by sviet2k** [comment]
Thanks for answer.

Here is the log:
https://pastebin.com/WcayxCmi

The error is:
2020-10-01 08:37:13.539 T:6621   ERROR: CCurlFile::Open failed with code **403** for http://asia-vn.googleapicdn.com/v1.0/st04/aa15f0c7fd187500136563004d44e7f2/gI91T4L2M3AP9TriBZINGw/c/a/f/42/905/63201c646b1c89433527a39d90542fac/hls-h264-480p/playlist.m3u8:
May be this link is blocked in foreign countries.

Thanks again for your help

**Comment by billythekids** [comment]
I got forbidden as well lol

**Comment by sviet2k** [comment]
It's great ... for me that we have the same issue :D
