### ISSUE TITLE
Nhờ bác sửa lỗi X trên kho TVHay

### ISSUE THREAD

**Issue by vuduytaidb** [billythekids/plugin.video.bimozie#21]
Mấy hôm nay TVHay bị lỗi báo X đỏ trên các mục : Thể loại, Quốc gia, Phim bộ ,Phim lẻ,  Phim mới, Phim thuyết minh.  2 mục thể loại và quốc gia vào trong cũng bị lỗi báo X đổ .  Chỉ riêng mục trang chủ vào các phim hiện sẵn ở add-on thì xem được. 
Mong nhận được sự giúp đỡ của bác
Cảm ơn

**Comment by billythekids** [comment]
Fixed 👍
