### ISSUE TITLE
add phim site to bimoie

### ISSUE THREAD

**Issue by minhgi** [billythekids/plugin.video.bimozie#24]
I found this site with alot of uslt release and most recent titles.  Can you add to the addon.

https://mobile.coivl.net/

Please re add or fix these phim site.  They were used to be in the addon.  I double check these site on the web and seem to up and working.  Seem they just move the domain or change the site name.  All these site have the long tien and thuy minh dub.

https://phim7z.tv/
http://tvhayzz.org/
https://www.phimmedia.info/
http://phim.vkool.net/

**Comment by billythekids** [comment]
i couldnt access to coivl 
others sites have been fixed

**Comment by minhgi** [comment]
> i couldnt access to coivl
> others sites have been fixed

is it hard to extract the in from it?  I could access the site without any problem for coil.net

confirmed working. 
phim7z.tv
tvhayzz.org
vkool

phommedia could be scrap but don't show the link.  thanks very much.

**Comment by billythekids** [comment]
Fixed
