### ISSUE TITLE
Nhờ bác sửa giúp tvhay với

### ISSUE THREAD

**Issue by vuduytaidb** [billythekids/plugin.video.bimozie#25]
[kodi.log](https://github.com/billythekids/plugin.video.bimozie/files/5475287/kodi.log)
Các thư mục lỗi X sau khi cập nhật bản mới nhất hôm nay không xem được nữa chỉ còn New Movies ở giao diện ngoài là xem được.
Mong bạn sửa giúp 
Cảm ơn bạn nhiều

**Comment by vuduytaidb** [comment]
![Screenshot_2020-11-02-20-20-44-009_com microsoft skydrive](https://user-images.githubusercontent.com/64639394/97872766-2b3a6f00-1d49-11eb-8b8d-0b1011207f4d.jpg)

**Comment by billythekids** [comment]
fixed
