### ISSUE TITLE
Tvhay lỗi S.Pro

### ISSUE THREAD

**Issue by vuduytaidb** [billythekids/plugin.video.bimozie#27]
Server S.Pro không xem được. Màn hình thì thì thời gian vẫn chạy mà hình không có , chuyển sang trình chạy VCL từ Kodi cũng không chạy được. Trên web vẫn xem được bình thường. Server R.Pro thì xem được nhưng xem chất lượng 720P thì giật không xem được chỉ xem được 480P. Mạng Viettelnhà mình  khá khỏe.
Cảm ơn
![Screenshot_2020-11-15-07-34-12-905_org xbmc kodi](https://user-images.githubusercontent.com/64639394/99160119-5ee8a200-2716-11eb-8c86-8c592d66737b.jpg)

**Comment by billythekids** [comment]
Fixed
