### ISSUE TITLE
Nhờ bác xem giúp lỗi tvhay

### ISSUE THREAD

**Issue by vuduytaidb** [billythekids/plugin.video.bimozie#28]
S.Pro không xem được. R.Pro xem được nhưng giật lắm. Cảm ơn và mong nhận được sự giúp đỡ của bác 
https://drive.google.com/file/d/12UXeXpnYSToIcvi0vSpOxpgZiewRE6Ki/view?usp=drivesdk

**Comment by billythekids** [comment]
Fixed
