### ISSUE TITLE
Nếu add thêm kênh bóng đá thuckhuya.tv nữa là hay

### ISSUE THREAD

**Issue by kevinkieu** [billythekids/plugin.video.bimozie#33]
Nếu add thêm kênh bóng đá thuckhuya.tv nữa là hay. Cảm ơn bạn đã cho ra cái addon rất tuyệt cho Kodi.

**Comment by billythekids** [comment]
Đã supported,  sẽ ra sớm trên kodi 19 nha

**Comment by billythekids** [comment]
Đã cập nhật trên 1.0.2 cho kodi 19
