### ISSUE TITLE
Need help for anime 47

### ISSUE THREAD

**Issue by sviet2k** [billythekids/plugin.video.bimozie#34]
Hi Billy,

If you have time, please help me to resolve the link from Anime 47 👍 

Here is the output to be used to get the link:

 <script src="https://anime47.com/ads/player/v/8.8.2/jwplayer.js?v=9" type="text/javascript"></script><script type="text/javascript">jwplayer.key = "ITWMv7t88JGzI0xPwW8I0+LveiXX9SWbfdmt0ArUSyc=";</script><div id="player">Đang tải phim...</div><script type="text/javascript">var thanhhoa = atob("eyJjdCI6IlV4cmZiRVB2bGw4SjgxUHpjS21kMGRhSW5TYWQ2VHpcL2RiMUNqU2V3NUpkbWxMRkdIcnZmSGVYSmJSTGhjWkNrdmlHRHRXcGlTNzJPNUV4U0JDckljUG9ROGQ2UitTT1oyVU9GUEFRRHg1c2szV2FWMkh4UVFwTHl6WENxZm5QVyIsIml2IjoiZDc0NWI4Zjg0MzdmN2U4NTNjZDU4MTYzZTgzMjY3MDgiLCJzIjoiMjFmYjQ1YzE5N2E2M2IyZSJ9");var daklak = JSON.parse(CryptoJS.AES.decrypt(thanhhoa, "caphedaklak", { format: CryptoJSAesJson }).toString(CryptoJS.enc.Utf8));var player = jwplayer('player').setup({"file": daklak,skin:{name:"tube",active:"#0f948d",inactive:"#0f948d",},"androidhls": true,"playbackRateControls":true,"mute":false,"autostart":"true","preload":"none","cast":{"appid":"00000000"},"base":".","volume":100,"width":"100%","height":"100%",androidhls:true,"image":"https://anime47.com/tool/googlevid/play.jpg"});player.addButton("https://anime47.com/ads/player/skip-forward.svg","Skip OP/ED",function(){skip_time=player.getPosition()+90;player.seek(skip_time)},"skipButton");player.addButton("https://anime47.com/ads/player/forward.svg","Next 10s",function(){player.seek(player.getPosition()+10);},"Next 10s");player.addButton("https://anime47.com/ads/player/backward.svg","Back 10s",function(){player.seek(player.getPosition()-10);},"Back 10s");</script> 

I tried to use gibberishAES to decode "thanhhoa" with key = "caphedaklak" but it fails.

Thanks in advance for your help.

**Comment by billythekids** [comment]
:D i'm working on this site as well, but currently couldn't mange to buy me time to continue

**Comment by sviet2k** [comment]
Great. Take your time. Don't rush :) 👍

**Comment by sviet2k** [comment]
I just find the solution. I would like to share with you to save your time:

			m = re.search('atob\("(.*?)"',p)
			if m:
				tt = base64.b64decode(m.group(1))
				enc_data = utils.json.loads(tt)
				ciphertext = 'Salted__' + enc_data['s'].decode('hex') + base64.b64decode(enc_data['ct'])
				ciphertext = base64.b64encode(ciphertext)
				print utils.gibberishAES(ciphertext, 'caphedaklak')

**Comment by billythekids** [comment]
Nice, it works perfectly :D
Many thank
