### ISSUE TITLE
Fix lỗi

### ISSUE THREAD

**Issue by vuduytaidb** [billythekids/plugin.video.bimozie#35]
Mong bác kiểm tra và fix lỗi để xem Tết. TVhay không xem được nữa rồi.
Chúc bác với gia đình năm mới hạnh phúc và thành công.
Cảm ơn bác nhiều

**Comment by thanhnhaxinhdep** [comment]
mình cũng gặp phải lỗi tương tự, cả server S. và R. đều không xem được ạ.

**Comment by dungkent2101** [comment]
tvhays.org đã đổi domain sang tvhai.org mong ad fix sớm.

**Comment by billythekids** [comment]
Đã fix
