### ISSUE TITLE
Chào bác chủ Bimozie !

### ISSUE THREAD

**Issue by vuduytaidb** [billythekids/plugin.video.bimozie#37]
Kodi 19 đã hoàn thành thử nghiệm và trong thời gian rất gần sẽ phát hành chính thức, em tải về cài đặt để dùng thì add-on Bimozie không tương thích với Kodi 19. Em tìm hiểu thì được biết phiên bản Kodi 19 sẽ thay đổi khá nhiều mã nguồn so với phiên bản Kodi 18.9 hện nay nên tất cả các add-on đều phải viết lại để tương thích với nó.
Không biết bác có dự định sẽ tiếp tục hỗ trợ tiếp Bimozie lên được Kodi 19 hay không? 
Cảm ơn bác rất nhiều vì đã viết ra add-on rất tuyệt vời.

**Comment by billythekids** [comment]
Mình đang upgrade lên (tầm hơn 2 tháng trước) nhưng chưa làm đc bao nhiêu cả
Với lại vừa support cái đang làm và upgrade lên đòi hỏi nhiều thời gian quá nên cũng ko thể xong sớm đc

**Comment by vuduytaidb** [comment]
Vâng! Cảm ơn bác rất nhiều và mong sớm nhận được bản update cho Kodi 19 của bác

**Comment by billythekids** [comment]
đã có version mới cho kodi 19 👍

**Comment by vuduytaidb** [comment]
Em cảm ơn bác nhiều nhé! Chúc bác với gia đình mạnh khỏe và hạnh phúc nhé

Vào 5:46 SA, Th 6, 26 thg 2, 2021 Billy Nguyen <notifications@github.com>
đã viết:
