### ISSUE TITLE
Nhờ bác kiểm tra 

### ISSUE THREAD

**Issue by vuduytaidb** [billythekids/plugin.video.bimozie#38]
Bản cập nhật 1.0.2 không cập nhật được em vào cập nhật được mà khi ấn cập nhật được mà ấn vào ô cài đặt thì add-on Bimozie mất luôn ( bị xoá ) cài đặt lại cũng không được. Em phải vào website gihub để tải plugin zip 1.0.2 để cài mới được. Mà kể cả có cài thì nó luôn biểu tượng có bản cập nhật.
Mong bác xem giúp
![SAVE_20210227_083935](https://user-images.githubusercontent.com/64639394/109372049-0e1e4300-78da-11eb-8784-7930fd200862.jpg)
![SAVE_20210227_083948](https://user-images.githubusercontent.com/64639394/109372051-10809d00-78da-11eb-8ae9-565b655af2b7.jpg)
![SAVE_20210227_085449](https://user-images.githubusercontent.com/64639394/109372052-124a6080-78da-11eb-8ece-83b1c33fa56a.jpg)

**Comment by billythekids** [comment]
Bác gỡ bản cài cũ ra rồi cài lại từ repo là đc. Nhớ update repo trước 

![image](https://user-images.githubusercontent.com/1701128/109388989-ef04cd00-793c-11eb-8154-c9313e3bc420.png)

**Comment by vuduytaidb** [comment]
Bản cập nhật ok rồi cảm ơn bác

Vào 12:25 SA, CN, 28 thg 2, 2021 Billy Nguyen <notifications@github.com> đã
viết:
