### ISSUE TITLE
Error: Unknown addon id 'service.liveproxy' (smamuhh1metro.py)

### ISSUE THREAD

**Issue by sviet2k** [billythekids/plugin.video.bimozie#4]
Hi Billy,

I received error when trying the smamuh link in hphim. (Bimozie version 0.2.20)

Here is the error:
smamuhh1metro.py line 7
Unknown addon id 'service.liveproxy'

I guess that I have to install the liveproxy addon ? Can you please help me to fix this issue?

Thank you

**Comment by billythekids** [comment]
this feature is experimental :| cause its using streamlink which supporting to stream drm content.
You can try with it 
1. Download repo https://github.com/back-to/repo/raw/master/repository.back-to/repository.back-to-5.0.0.zip
2. Install this repo 
3. Install liveproxy from this repo
4. Test with it

Only downside while using streamlink is your video not seek-able

**Comment by sviet2k** [comment]
Thanks for the info.
I installed the liveproxy and it's working 👍 but as you mentioned that there is no seek-able and no resume option. A little bit annoying because you have to watch the episode from A-Z :(
I tried other option (with the header) but it does not work.

Thanks again for your help.

**Comment by billythekids** [comment]
Yeah i know it, but i still dont find any better solution. Vod with drm becomes common now :(
