### ISSUE TITLE
Bimozie gặp lỗi

### ISSUE THREAD

**Issue by vuduytaidb** [billythekids/plugin.video.bimozie#47]
Nhờ bác kiểm tra sửa lỗi không còn xem được bất kỳ trang phim nào nữa. Em kodi 19 cảm ơn bác

**Comment by billythekids** [comment]
New version released !

**Comment by uzumakinaruto2109** [comment]
Hi Kodi 19 version 1.0.16 bị lỗi lại rồi ạ. Click vào site phim nào cũng ra màn hình trắng cả
