### ISSUE TITLE
90m.tv: pegasus site problem

### ISSUE THREAD

**Issue by boxkim14** [billythekids/plugin.video.bimozie#5]
Hi Billy,

We have HTTP 403 error when trying to play pegasus link from site 90m.tv.
The referer in header is not ''h t t p s://live.90m.tv'
but look like as below:
H "referer: h t t ps://live.90m.tv/5dbdfd8ea6651b37b974ae0c.html"

I hope this info can help you to fix the 403 error.

Thank you

**Comment by billythekids** [comment]
Hi boxkim14,

Thank for you report, unfortunately i couldn't test it right now, either the game is too late that i couldn;t wait to test it or i wasnt at home.

I will try to fix it as soon as i can if you please provide me the correct information

Rg,
Billy

**Comment by billythekids** [comment]
Fixed in 0.3.1 Issue close
