### ISSUE TITLE
Bimozie 1.0.16 không hoạt động

### ISSUE THREAD

**Issue by uzumakinaruto2109** [billythekids/plugin.video.bimozie#50]
Hi bạn Bimozie trên Kodi 19 version 1.0.16 bị lỗi ạ , khi click vào site phim nào cũng ra màn hình trắng cả.
Còn khi mình thử dùng lại version 1.0.14 thì vẫn lấy được danh sách thể loại và phim, chỉ khi click vào từng phim thì bị trắng.

**Comment by billythekids** [comment]
Bạn check lại xem trên 1.0.18 xem còn bị ko

**Comment by billythekids** [comment]
Đã sửa 👍
