### ISSUE TITLE
Can't update to ver 1.0.18 on Kodi 19.1

### ISSUE THREAD

**Issue by win123139** [billythekids/plugin.video.bimozie#51]
when auto update get error "xbmc.python version 2.1.0 could not be satisfied"
how can i fix this. I use Kodi 19.1

**Comment by billythekids** [comment]
Đã sửa 👍

**Comment by win123139** [comment]
> 



> Đã sửa 👍

I still get error  "xbmc.python version 2.1.0 could not be satisfied" when update to 1.0.19
I using ver 1.0.16 in kodi 19.1
