### ISSUE TITLE
Phụ đề phim1080

### ISSUE THREAD

**Issue by truonggiang88** [billythekids/plugin.video.bimozie#54]
Vẫn ko hiện sub trang 1080z ad ơi
![16392413372096120998890793811685](https://user-images.githubusercontent.com/74853571/145684801-d79d661c-e712-409e-b910-e3e48430e15b.jpg)
![16392414364555767161860106611896](https://user-images.githubusercontent.com/74853571/145684820-9479bf5b-89a6-4106-a431-daa0987cb077.jpg)

**Comment by billythekids** [comment]
Fixed
