### ISSUE TITLE
DongPhim new link

### ISSUE THREAD

**Issue by sviet2k** [billythekids/plugin.video.bimozie#7]
Hi Billy,

DongPhim has a lot of new link as below:
h t t p s://dong phim.net/detail/iframe?id=QbMIe28bA

I try to convert it (see pastebin) but fail: Kodi returns error: Error to load first segmentation.
h t t p s://pastebin.com/g9TnFnDF

Do you know how to resolve this new link?

Thank you

**Comment by billythekids** [comment]
Its missing hash part
All streamings from idocdn, hydrax... are encrypted, and kodi is not allow to play kind of link. Basically you need other tool or plugins to able to bypass DRM content

**Comment by chughe** [comment]
Filmfast and phimgi.net also can not play link! Can you fix that pls!

**Comment by billythekids** [comment]
Some of hosts are using encrypting service. Its impossible to play these links except using third party library inside kodi  and you aint able to seek or do anything. One of most downside of it

**Comment by sviet2k** [comment]
Do you know which third party lib can play these links?
streamlink fails to play it. :(
It's better to able to play it without seek than nothing :)

**Comment by L2501** [comment]
Example script to play these streams:  
https://github.com/L2501/script.gslug.player

**Comment by sviet2k** [comment]
Thanks L2501 for the info. I will try to  integrate it.

**Comment by billythekids** [comment]
> Example script to play these streams:
> https://github.com/L2501/script.gslug.player

Nice, i will include it in my next release. Many thanks @L2501
