### ISSUE TITLE
New type of link in bilu

### ISSUE THREAD

**Issue by sviet2k** [billythekids/plugin.video.bimozie#9]
Hi billy,

In bilutv moi, there is a new type of link:

h t t p s://h2.vtvhub.com/hls/644c01c871fa3c98f4e65a6b65c1a268/644c01c871fa3c98f4e65a6b65c1a268.playlist.
 m3u8

that addon cannot play.

If you have time, please take a look on this. :)

Thanks

**Comment by billythekids** [comment]
Can you provide me a name of movie so i can test it?

**Comment by sviet2k** [comment]
Bilu stops using this type of link . :)
Sorry for this.
